- name: Install and configure web server
  hosts: backend
  become: true
  user: ansible
  gather_facts: no
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: prelimnary
   - role: hardening
   - role: backend
   - role: cleanup
