- name: Install and configure web server
  hosts: webserver
  become: true
  user: ansible
  gather_facts: no
  become_method: sudo
  vars_files:
   - group_vars/all     
  roles:
   - role: prelimnary
   - role: hardening
   - role: web
   - role: cleanup
