- name: Install and configure marathon
  hosts: 192.168.1.81
  become: true
  user: ansible
  gather_facts: no
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: marathon
   - role: cleanup
