- name: Install and configure marathon
  hosts: marathon
  become: true
  user: ansible
  gather_facts: no
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: prelimnary
   - role: hardening
   - role: marathon
   - role: cleanup
