- name: Install and configure zookeper
  hosts: zookeper
  become: true
  user: ansible
  gather_facts: no
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: prelimnary
   - role: hardening
   - role: zookeper
   - role: cleanup
