---
- name: installing java  development kit
  apt:
   name: default-jdk
   state: present
   update_cache: yes

- name: Ensure Group tomcat exists
  group:
   name: tomcat
   state: present

- name: creating tomcat user
  user: 
   name: tomcat
   state: present
   shell: /bin/false
   group: tomcat
   home: /opt/tomcat

- name: Download tomcat archive
  get_url:
   url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.10/bin/apache-tomcat-9.0.10.tar.gz
   dest: /tmp
   mode: 0777

- name: unzip and install
  unarchive:
   src: /tmp/apache-tomcat-9.0.10.tar.gz
   dest: /opt/tomcat/
   extra_opts: [--strip-components=1]
   remote_src: yes

- name: change ownership of /opt/tomcat
  file:
   path: /opt/tomcat
   owner: tomcat
   group: tomcat
   mode: 0755
   recurse: yes

- name: Add systemd file
  template:
   src: tomcat.service.j2
   dest: /etc/systemd/system/tomcat.service

- name: restart and daemon reload tomcat, in all cases, also issue daemon-reload to pick up config changes
  systemd:
   state: restarted
   daemon_reload: yes
   name: tomcat


