---
- name: Apache server installing
  apt:
    name: apache2
    state: present

- name: changing the httpd port to 8080 from 80 
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen'
    line: Listen 8080
 
- name: copying webpage from ansible to server
  copy:
    src: /home/ansible/playbooks/roles/web/files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'

